### ISSUE TITLE
rearx doesn't restore terminal state when it exits on 'q'

### ISSUE THREAD

**Issue by yurivict** [garak92/rearx#4]
Please observe how the cursor was black before ```rearx``` and disappeared after it.

It reappears after ```reset``` is called.

https://user-images.githubusercontent.com/271906/112069349-ead96300-8b28-11eb-8da2-7330b0a769a8.mp4

1.0.3
FreeBSD 12.2
xfce4

**Comment by garak92** [comment]
Fixed on https://github.com/garak92/rearx/commit/20bfbd947b0bba5079a72f041bc47567564707c8
